- name: Update apt list
  apt:
    update_cache: yes

- name: Install desired packages
  apt:
    update_cache: no
    name: '{{ ais_packages }}'
    state: present

- name: Configure ulimits for host
  pam_limits:
    domain: '*'
    limit_item: "{{ item.limit_item }}"
    limit_type: "{{ item.limit_type }}"
    value: "{{ item.value }}"
  with_items:
    - "{{ ais_pam_limits }}"

- name: Tweak sysctl.conf
  sysctl:
    sysctl_file: /etc/sysctl.d/90-ais.conf
    reload: yes
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ ais_host_sysctl }}"

- name: Set host mtu in netplan
  template:
    src: 01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ ais_host_mtu }}"
  register: netplan

- name: Apply netplan if changed
  command: netplan apply
  when: netplan.changed

- name: Set CPU frequency governor to requested mode
  command: cpupower frequency-set -r -g {{ ais_cpufreq_governor }}

- name: Make sure we have a /usr/local/bin
  file:
    dest: /usr/local/bin
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install /usr/local/bin/ais_host_config.sh
  template:
    src: ais_host_config.sh.j2
    dest: /usr/local/bin/ais_host_config.sh
    owner: root
    group: root
    mode: 0755

- name: Create aishostconfig systemctl unit
  copy:
    src: aishostconfig.service
    dest: /etc/systemd/system
    mode: 0444
  register: configservice

- name: (Re)start aishostconfig service
  systemd:
    name: aishostconfig
    daemon-reload: yes
    enabled: yes
    state: restarted
  when: configservice.changed




  