apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "chart.name" . }}-r
rules:
  - apiGroups: [""]
    resources: ["secrets", "daemonsets", "services", "pods"]  # XXX TODO too liberal!
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
