apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "ais.name" . }}-r
rules:
  - apiGroups: [""]
    resources: ["secrets", "daemonsets", "services", "pods", "configmaps"]
    verbs: ["*"]  # XXX TODO thid is too liberal!
