apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ais.name" . }}-neproxy
data:
  ais.json: |-
{{ include "ne_proxy.config" .   | indent 4 }}
  set_uuid_env.sh: |-
{{ include "common.set_uuid_env" . | indent 4 }}
