apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ais.name" . }}-proxy
data:
  ais.json: |-
{{ include "proxy.config" .   | indent 4 }}
  set_initial_primary_proxy_env.sh: |-
{{ include "proxy.set_initial_primary_proxy_env" . | indent 4 }}
  set_uuid_env.sh: |-
{{ include "common.set_uuid_env" . | indent 4 }}
